### ISSUE TITLE
[Suggestion] New Animations

### ISSUE THREAD

**Issue by HugoBDesigner** [HugoBDesigner/Mari0-Community-Edition#59]
- [ ] [Let players use other portal IDs](https://github.com/HugoBDesigner/Mari0-Community-Edition/issues/58);
 - [ ] [Integrate Turret's Additional Animations](https://github.com/HugoBDesigner/Mari0-Community-Edition/issues/56);
 - [ ] [Enable/Disable individual colors of portals, clear portals](https://github.com/HugoBDesigner/Mari0-Community-Edition/issues/52);
 - [ ] [Allow mappacks to prevent portal resetting](https://github.com/HugoBDesigner/Mari0-Community-Edition/issues/49);
 - [ ] [Port HEC Environmental Triggers as Conditions, and Commanders as Actions](https://github.com/HugoBDesigner/Mari0-Community-Edition/issues/12).
